INSERT INTO products (id, name, description, price) VALUES
                                                        (1, 'Laptop', '15 inch, 8GB RAM, 256GB SSD', 799.99),
                                                        (2, 'Smartphone', '6 inch, 4GB RAM, 64GB Storage', 299.99),
                                                        (3, 'Headphones', 'Over-ear, noise-cancelling', 99.99),
                                                        (4, 'Keyboard', 'Mechanical, RGB backlight', 49.99),
                                                        (5, 'Mouse', 'Wireless, 16000 DPI', 29.99),
                                                        (6, 'Monitor', '24 inch, 1080p resolution', 149.99),
                                                        (7, 'Tablet', '10 inch, 4GB RAM, 128GB Storage', 399.99),
                                                        (8, 'Smartwatch', 'Heart rate, GPS', 199.99),
                                                        (9, 'Camera', 'DSLR, 24MP', 499.99),
                                                        (10, 'Printer', 'Laser, color', 199.99),
                                                        (11, 'Router', 'Dual-band, 5GHz', 79.99),
                                                        (12, 'Speaker', 'Bluetooth, 10W', 39.99),
                                                        (13, 'Hard Drive', '1TB, SSD', 119.99),
                                                        (14, 'RAM', '16GB, DDR4', 59.99),
                                                        (15, 'Graphics Card', '8GB, GDDR6', 399.99),
                                                        (16, 'Microphone', 'USB, cardioid pattern', 69.99),
                                                        (17, 'Webcam', '1080p, autofocus', 49.99),
                                                        (18, 'Charger', 'USB-C, fast charging', 19.99),
                                                        (19, 'HDMI Cable', '2m, 4K support', 9.99),
                                                        (20, 'Backpack', 'Laptop compartment, waterproof', 59.99);